spring:
  application:
    name: telegram-rent-admin-image-bot

telegram:
  webhookUrl: https://f096-185-123-165-192.ngrok-free.app/webhook
  botPath: /webhook

server:
  port: 8081

logging:
  level:
    web: debug


